IAC-2232: add retries to argo deploy workflow (#33)
* IAC-2232: add retries to argo deploy workflow

* IAC-2260: fix hotfix target point in dev and exit deploy with non-fmt conventional commit

diff --git a/.github/workflows/deploy-argo-application.yml b/.github/workflows/deploy-argo-application.yml
--- a/.github/workflows/deploy-argo-application.yml
+++ b/.github/workflows/deploy-argo-application.yml
@@ -181,6 +181,8 @@ jobs:
           GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN  }}'
 
       - name: Determine target revision
+        env:
+         BRANCH: ${{ steps.extract_branch.outputs.branch }}
         id: determine_revision
         run: |
           if [[ "${{ steps.semantic.outputs.new_release_published }}" == 'true' ]]; then
@@ -188,7 +190,7 @@ jobs:
           elif [[ "${{ inputs.semantic_new_release_version }}" != '' ]]; then
             echo "target_revision=${{ inputs.semantic_new_release_version }}" >> $GITHUB_OUTPUT
           elif [[ "${{ inputs.environment }}" == 'dev' ]]; then
-            echo "target_revision=main" >> $GITHUB_OUTPUT
+            echo "target_revision=$BRANCH" >> $GITHUB_OUTPUT
           else
             echo "target_revision=" >> $GITHUB_OUTPUT
           fi
@@ -214,11 +216,47 @@ jobs:
           if [ -n "$TARGET_REVISION" ]; then
             echo -e "\n- op: 'replace'\n  path: '/spec/source/targetRevision'\n  value: '$TARGET_REVISION'" >> $APPLICATION_PATH/application.yaml
             kustomize build $APPLICATION_PATH > $APPLICATION_FILE_NAME
-            argocd app create -f  $APPLICATION_FILE_NAME --auth-token $ARGOCD_AUTH_TOKEN --server $SERVER_ADDRESS --upsert
+
+            set +e
+            MAX_RETRIES=5
+            RETRY_DELAY=5
+            ARGO_GENERIC_ERR_EXIT_CODE=20
+            DEPLOY_COMMAND="argocd app create -f  $APPLICATION_FILE_NAME --http-retry-max $MAX_RETRIES --auth-token $ARGOCD_AUTH_TOKEN --server $SERVER_ADDRESS --upsert"
+            
+            deploy_with_retries() {
+              local attempt=1
+              local exit_code
+              while [ $attempt -le $MAX_RETRIES ]; do
+                $DEPLOY_COMMAND
+                exit_code=$?
+                if [ $exit_code -eq $ARGO_GENERIC_ERR_EXIT_CODE ]; then
+                  echo "::warning::Attempt $attempt failed with exit code $ARGO_GENERIC_ERR_EXIT_CODE. Retrying in $RETRY_DELAY seconds..."
+                  sleep $RETRY_DELAY
+                  ((attempt++))
+                else
+                  break
+                fi
+              done
+              return $exit_code
+            }
+
+            deploy_with_retries
+            exit_code=$?
+
+            set -e
+            if [ $exit_code -eq 0 ]; then
+              echo "Application deployed successfully!"
+            elif [ $exit_code -eq $ARGO_GENERIC_ERR_EXIT_CODE ]; then
+              echo "::error::Application deploy failed after $MAX_RETRIES retries."
+              exit $exit_code
+            else
+              exit $exit_code
+            fi
           else
             echo -e "::warning:: Deploy Announcement:"
             echo -e "::warning:: The release has been not deployed, it appears there are no commits following the conventional commit guidelines for this release."
             echo -e "::warning:: To ensure future releases are properly versioned and tagged, please refer to the https://mynovu.atlassian.net/wiki/x/BQDS5w#Style-Guide for detailed instructions on how to format your commits."
             echo -e "::warning:: We recommend following these conventions to maintain consistency and automation in versioning and release management."
             echo -e "::warning:: Thank you!"
+            exit 1
           fi
