IAC-2232: add retries to argo deploy workflow

diff --git a/.github/workflows/deploy-argo-application.yml b/.github/workflows/deploy-argo-application.yml
--- a/.github/workflows/deploy-argo-application.yml
+++ b/.github/workflows/deploy-argo-application.yml
@@ -214,7 +214,42 @@ jobs:
           if [ -n "$TARGET_REVISION" ]; then
             echo -e "\n- op: 'replace'\n  path: '/spec/source/targetRevision'\n  value: '$TARGET_REVISION'" >> $APPLICATION_PATH/application.yaml
             kustomize build $APPLICATION_PATH > $APPLICATION_FILE_NAME
-            argocd app create -f  $APPLICATION_FILE_NAME --auth-token $ARGOCD_AUTH_TOKEN --server $SERVER_ADDRESS --upsert
+
+            set +e
+            MAX_RETRIES=5
+            RETRY_DELAY=5
+            ARGO_GENERIC_ERR_EXIT_CODE=20
+            DEPLOY_COMMAND="argocd app create -f  $APPLICATION_FILE_NAME --http-retry-max $MAX_RETRIES --auth-token $ARGOCD_AUTH_TOKEN --server $SERVER_ADDRESS --upsert"
+            
+            deploy_with_retries() {
+              local attempt=1
+              local exit_code
+              while [ $attempt -le $MAX_RETRIES ]; do
+                $DEPLOY_COMMAND
+                exit_code=$?
+                if [ $exit_code -eq $ARGO_GENERIC_ERR_EXIT_CODE ]; then
+                  echo "::warning::Attempt $attempt failed with exit code $ARGO_GENERIC_ERR_EXIT_CODE. Retrying in $RETRY_DELAY seconds..."
+                  sleep $RETRY_DELAY
+                  ((attempt++))
+                else
+                  break
+                fi
+              done
+              return $exit_code
+            }
+
+            deploy_with_retries
+            exit_code=$?
+
+            set -e
+            if [ $exit_code -eq 0 ]; then
+              echo "Application deployed successfully!"
+            elif [ $exit_code -eq $ARGO_GENERIC_ERR_EXIT_CODE ]; then
+              echo "::error::Application deploy failed after $MAX_RETRIES retries."
+              exit $exit_code
+            else
+              exit $exit_code
+            fi
           else
             echo -e "::warning:: Deploy Announcement:"
             echo -e "::warning:: The release has been not deployed, it appears there are no commits following the conventional commit guidelines for this release."
